name: Heroku Dyno Switcher
on:
  schedule:
  - cron: "0 0 1,15 * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
          cache: 'pip'
      - name: Installing heroku3
        run: pip install -r requirements.txt
      - name: Switching the dyno
        run: python3 script_noloop.py
        env:
          FIRST_PROCESSTYPE: ${{ secrets.FIRST_PROCESSTYPE }}
          FIRST_A_APIKEY: ${{ secrets.FIRST_A_APIKEY }}
          FIRST_A_APPNAME: ${{ secrets.FIRST_A_APPNAME }}
          FIRST_B_APIKEY: ${{ secrets.FIRST_B_APIKEY }}
          FIRST_B_APPNAME: ${{ secrets.FIRST_B_APPNAME }}
          SECOND_PROCESSTYPE: ${{ secrets.SECOND_PROCESSTYPE }}
          SECOND_A_APIKEY: ${{ secrets.SECOND_A_APIKEY }}
          SECOND_A_APPNAME: ${{ secrets.SECOND_A_APPNAME }}
          SECOND_B_APIKEY: ${{ secrets.SECOND_B_APIKEY }}
          SECOND_B_APPNAME: ${{ secrets.SECOND_B_APPNAME }}
          THIRD_PROCESSTYPE: ${{ secrets.THIRD_PROCESSTYPE }}
          THIRD_A_APIKEY: ${{ secrets.THIRD_A_APIKEY }}
          THIRD_A_APPNAME: ${{ secrets.THIRD_A_APPNAME }}
          THIRD_B_APIKEY: ${{ secrets.THIRD_B_APIKEY }}
          THIRD_B_APPNAME: ${{ secrets.THIRD_B_APPNAME }}
          FOURTH_PROCESSTYPE: ${{ secrets.FOURTH_PROCESSTYPE }}
          FOURTH_A_APIKEY: ${{ secrets.FOURTH_A_APIKEY }}
          FOURTH_A_APPNAME: ${{ secrets.FOURTH_A_APPNAME }}
          FOURTH_B_APIKEY: ${{ secrets.FOURTH_B_APIKEY }}
          FOURTH_B_APPNAME: ${{ secrets.FOURTH_B_APPNAME }}
          FIFTH_PROCESSTYPE: ${{ secrets.FIFTH_PROCESSTYPE }}
          FIFTH_A_APIKEY: ${{ secrets.FIFTH_A_APIKEY }}
          FIFTH_A_APPNAME: ${{ secrets.FIFTH_A_APPNAME }}
          FIFTH_B_APIKEY: ${{ secrets.FIFTH_B_APIKEY }}
          FIFTH_B_APPNAME: ${{ secrets.FIFTH_B_APPNAME }}
